services:
  finally:
    build: .
    image: finally
    container_name: finally
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./db:/app/db
    restart: unless-stopped
